### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [jaywcjlove/awesome-uikit#27]
Hi, I foud a few broken links:

- [x] https://javascriptreport.com/the-ultimate-guide-to-javascript-frameworks/ (file: README.md, error: ECONNRESET)
- [x] https://ant-move.github.io/website/ (file: README.md, status code: 404)
- [x] https://tencent.github.io/wepy/ (file: README.md, status code: 404)
- [x] https://yysun.github.com/apprun (file: README.md, status code: 404)
- [x] http://avalonjs.coding.me/ (file: README.md, error: ENOTFOUND)
- [x] http://leeoniya.github.io/domvm/ (file: README.md, status code: 404)
- [x] http://moonjs.ga/ (file: README.md, error: ENOTFOUND)
- [x] https://makajs.org (file: README.md, error: ECONNRESET)
- [x] http://purescript-pux.org/ (file: README.md, error: ENOTFOUND)
- [x] https://stemjs.org/ (file: README.md, error: CERT_HAS_EXPIRED)
- [x] https://material-components.github.io/material-web/demos/ (file: README.md, status code: 404)
- [x] https://fast.design (file: README.md, error: CERT_HAS_EXPIRED)
- [x] https://xy-ui.codelabo.cn/docs (file: README.md, status code: 404)
- [x] http://amazeui.org/react/ (file: README.md, error: ENOTFOUND)
- [x] https://www.sencha.com/products/extreact/ (file: README.md, status code: 404)
- [x] https://fannypack.style (file: README.md, error: ENOTFOUND)
- [x] https://garden.zendesk.com/react-components/ (file: README.md, status code: 404)
- [x] https://klarna.github.io/ui/ (file: README.md, status code: 404)
- [x] https://nice.textkernel.nl/react/ (file: README.md, error: ENOTFOUND)
- [x] https://precise-ui.io/ (file: README.md, error: ENOTFOUND)
- [x] https://jamesmfriedman.github.io/rmwc/ (file: README.md, status code: 404)
- [x] https://www.react-uwp.com (file: README.md, error: ECONNRESET)
- [x] http://kbuechl.github.io/react-uikit-components/ (file: README.md, error: ENOTFOUND)
- [x] https://stardust-ui.github.io/react/ (file: README.md, status code: 404)
- [x] https://zarm-web.netlify.com/ (file: README.md, status code: 404)
- [x] https://bootstrap-vue.github.io/ (file: README.md, status code: 404)
- [x] https://ecomfe.github.io/veui/components/ (file: README.md, status code: 404)
- [x] https://museui.github.io (file: README.md, error: ECONNREFUSED)
- [x] https://owl-ui.dengwb.com (file: README.md, error: EPROTO)
- [x] https://vuecomponent.github.io/ant-design/docs/vue/introduce/ (file: README.md, status code: 404)
- [x] https://ng-semantic.herokuapp.com/#/ (file: README.md, status code: 404)
- [x] https://vmware.github.io/clarity/ (file: README.md, status code: 404)
- [x] http://www.layui.com/ (file: README.md, error: ENOTFOUND)
- [x] http://m.sui.taobao.org/ (file: README.md, error: ECONNRESET)
- [x] http://www.supermgr.cn/ (file: README.md, error: ENOTFOUND)
- [x] http://t.amazeui.org/ (file: README.md, error: ENOTFOUND)
- [x] http://nowui.ivweb.io/ (file: README.md, status code: 410)
- [x] https://avocode.com/nachos-ui/ (file: README.md, status code: 404)
- [x] https://opensource-cards.github.io/binary-ui/ (file: README.md, status code: 404)
- [x] https://github.com/opensource-cards/binary-ui (file: README.md, status code: 404)
- [x] http://www.zdliu.com/ (file: README.md, error: ENOTFOUND)
- [x] http://jxy.me/react-antd-admin/ (file: README.md, status code: 404)
- [x] http://antd.sosout.com/home (file: README.md, status code: 404)
- [x] https://sample.rsuitejs.com/ (file: README.md, error: ERR_TLS_CERT_ALTNAME_INVALID)
- [x] https://d2admin.fairyever.com (file: README.md, error: EPROTO)
- [x] http://refined-x.com/Flow-UI/dashboard/index.html (file: README.md, status code: 404)
- [x] https://iview.github.io/iview-admin (file: README.md, status code: 404)
- [x] https://taylorchen709.github.io/vue-admin/ (file: README.md, status code: 404)
- [x] http://herozhou.coding.me/vue-framework-wz (file: README.md, error: ENOTFOUND)
- [x] https://pro.loacg.com (file: README.md, error: ENOTFOUND)
- [x] https://pmg1989.github.io/login (file: README.md, status code: 404)
- [x] https://doc.forestadmin.com/developer-guide/lumber.html (file: README.md, error: ENOTFOUND)
- [x] https://blackrockdigital.github.io/startbootstrap-sb-admin-2/pages/index.html (file: README.md, status code: 404)

**Comment by jaywcjlove** [comment]
@ndsvw thx!
